# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonemodel',
            name='Brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('iPhone', 'iPhone'), ('Xiaomi', 'Xiaomi'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('Realme', 'Realme')], max_length=20),
        ),
    ]
