# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200519_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonemodel',
            name='TahunRilis',
            field=models.IntegerField(max_length=4),
        ),
    ]
