# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonemodel',
            name='TahunRilis',
            field=models.IntegerField(),
        ),
    ]
